### ISSUE TITLE
Improve spacing in default theme.

### ISSUE THREAD

**Issue by Tropix126** [GeopJr/SveltePress#139]
One minor thing i've noticed about the default theme is that heading blocks aren't spaced, likely due to the CSS reset included in carbon. I think adding a bit of vertical margin here would give the document more space to "breathe" in the visual hierarchy.

Current styling
![image](https://user-images.githubusercontent.com/42101043/134791166-3c6aa598-a93a-4d57-a1d9-7f633be5f7e1.png)

`2rem 0` margins
![image](https://user-images.githubusercontent.com/42101043/134791184-cf4d9466-ad9d-4ac8-b216-53a038c41f84.png)

**Comment by Tropix126** [comment]
Codeblocks can be similarly improved with `line-height: var(--cds-code-01-line-height,1.34);`

![image](https://user-images.githubusercontent.com/42101043/134791406-31d12ea6-471f-44be-b125-bfc1d8666fe7.png)
![image](https://user-images.githubusercontent.com/42101043/134791407-399b5189-98a5-4e0a-8411-acfd0125a382.png)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of 2a2e4b8.
Feel free to re-open if there are additional changes needed!
