### ISSUE TITLE
[Nice to have] Option to filter files/folders

### ISSUE THREAD

**Issue by rdricco** [GeopJr/SveltePress#48]
Hi, do you think is possible to implement some sort of filter to what will be published?
I think would be cool to filter entire folders via config file or via frontmatter (ie. draft: true).

ps. Just found Sveltepress today, Thanks for your work, it's nice to see a svelte alternative for this.

**Comment by GeopJr** [comment]
Sounds good!

**Comment by GeopJr** [comment]
Thanks for the suggestion!

Support for `drafts` has been added! You can find its docs on the [guide](https://sveltepress.geopjr.dev/guide/02%20-%20writing/04%20-%20drafts).
